Health/recordssystem/__init__.py
from flask import Flask
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from flask_uploads import UploadSet, configure_uploads, IMAGES, patch_request_class
 
import os 


from models.enrollee import *
 


app = Flask(__name__)
app.config.from_pyfile('config.py')
app.config['ALLOWED_EXTENSIONS'] = set(['jpg', 'png', 'jpeg'])
app.config['UPLOADED_PHOTOS_DEST'] = os.getcwd()+'/static/passport'
photos = UploadSet('photos', IMAGES) 
configure_uploads(app, photos)
patch_request_class(app)

db.init_app(app)

login_manager = LoginManager()
login_manager.init_app(app)



login_manager.login_view = 'login.signin'
@login_manager.user_loader
def load_user(user_id):
    return Enrollee.query.get(int(user_id))



admin = Admin(app, name='Control Panel')
admin.add_view(ModelView(Enrollee, db.session))
admin.add_view(ModelView(Relative,db.session))
admin.add_view(ModelView(otp,db.session))

#admin.add_view(ModelView(Health_Care_Service_Provider, db.session))
admin.add_view(ModelView(payments_claims, db.session))
admin.add_view(ModelView(Histories,db.session))




from recordssystem.enrollee.views import hom
from recordssystem.auth.views import login
from recordssystem.dashboard.views import dash
from recordssystem.hcp.views import health_care_provider
from recordssystem.hmoss.views import hmos
from recordssystem.fhssmodule.views import fhss




app.register_blueprint(enrollee.views.hom)
app.register_blueprint(auth.views.login)
app.register_blueprint(dashboard.views.dash)
app.register_blueprint(hcp.views.health_care_provider)
app.register_blueprint(hmoss.views.hmos)
app.register_blueprint(fhssmodule.views.fhss)

Health/recordssystem/dashboard/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from flask_uploads import UploadSet, configure_uploads, IMAGES

from models.enrollee import * 
dash = Blueprint('dashboard', __name__)
photos = UploadSet('photos', IMAGES)

@dash.route('/dashboard')
@login_required
def dashboard():
    relatives = Relative.query.filter_by(creator=current_user.id).all()
    return render_template('./dashboard/index.html', relatives=relatives)


@dash.route('/processor',methods=['POST'])
@login_required
def processor():
    if current_user.registerd_relative == 4:
        flash('Access Denied!!!')
        return redirect(url_for('dashboard.dashboard'))
    else:
        fname = request.form['fname']
        mname = request.form['mname']
        lname = request.form['lname']
        dob = request.form['DoB']
        gender = request.form['Gender']
        blood_group=request.form['Blood_group']
        passport=request.files['passport']

        filename = photos.save(passport)
        url = photos.url(filename)
        new_membe = Relative(creator=current_user.id, first_name=fname,dob=dob,
        gender=gender,passport=url,blood_group=blood_group,
                             last_name=lname, middle_name=mname)
        current_user.registerd_relative +=1 
        db.session.add(new_membe)
        db.session.commit()
        flash('Record Saved')
        return redirect(url_for('dashboard.dashboard'))

Health/recordssystem/enrollee/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
import random



hom = Blueprint('homepage', __name__)

@hom.route('/')
def home():
    return render_template('./home/index.html')

Health/recordssystem/fhssmodule/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for,abort
from werkzeug.security import generate_password_hash, check_password_hash
import random
from models.Hcp import *
from models.enrollee import * 
import shortuuid
import nexmo


fhss = Blueprint('fhss', __name__)

def fhss_required():
    if current_user.fhss_role==False:
        return abort(404)
    else:
        pass

@fhss.route('/fhss')
@login_required
def fmain():
    fhss_required()
    #user = Enrollee.query.order_by(
    #Enrollee.date_registerd.desc()).all()
    user = Enrollee.query.filter_by(enrollee_role=True).all()
    hmos = Enrollee.query.filter_by(hmo_role=True).all()

    return render_template('./fhss/dashboard.html',user=user,hmos=hmos)
    
@fhss.route('/fenrollee')
@login_required
def fhenrol():
    fhss_required()
    user = Enrollee.query.filter_by(enrollee_role=True).all()
    return render_template('/fhss/enrollee/dashboard.html',user=user)
@fhss.route('/fhcp')
def fhcp():
    hcp = Enrollee.query.filter_by(hcp_role=True).all()
    return render_template('./fhss/hcp/hcp.html',hcp=hcp)

@fhss.route('/view_request/<int:id>')
def view_request(id):
    user = payments_claims.query.filter_by(Hmo_ID=id).all()
    return render_template('fhss/payments.html',user=user)


@fhss.route('/view_enrollee/<int:id>')
def view_enrollee(id):
    user = Enrollee.query.filter_by(id=id).first()
    return render_template('/fhss/enrollee/profile.html', user=user)


@fhss.route('/hcp_view/<int:id>')
def hcp_view(id):
    user = Enrollee.query.filter_by(id=id).first()
    return render_template('/fhss/hcp/profile.html', user=user)


@fhss.route('/view_history/<int:id>')
@login_required
def view_history(id):
    fhss_required()
    user = Histories.query.filter_by(Hospital_ID=id).all()
    return render_template('./fhss/hcp/view.html', user=user)





@fhss.route('/fprofile/<int:id>')
@login_required
def fprofile(id):
    fhss_required()
    user = Enrollee.query.filter_by(id=id).first()
    return render_template('/fhss/profile.html', user=user)

@fhss.route('/fhss/signup')
def fsignup():
    return render_template('fhss/signup/index.html')

Health/recordssystem/hcp/views.py
import random

import nexmo
import shortuuid
from flask import Blueprint, flash, jsonify, redirect, render_template,g,request, url_for,abort
from werkzeug.security import check_password_hash, generate_password_hash

from models.enrollee import *
from models.Hcp import *

health_care_provider = Blueprint('hcp', __name__)


NEXMO_API_KEY = '90389872'
NEXMO_API_SECRET = 'uwt4vYJX3ujMBj3r'

client=nexmo.Client(
	key=NEXMO_API_KEY,
	secret=NEXMO_API_SECRET
)

def logger(userid):
    user = Enrollee.query.filter_by(id=userid).first()
    post_cost = request.form['post_cost']
    ailment = request.form['ailment']
    user.post_cost += int(post_cost)
    user.ailment=ailment
    New_histories = Histories(Hospital_Name=current_user.hospital_name, Hospital_ID=current_user.id,
    Patient_name=user.first_name,Patient_nin=user.nin,Patient_fhss=user.fhss,post_cost=request.form['post_cost'],
                              ailment=request.form['ailment'])
    db.session.add(New_histories)
    db.session.commit()



def hcp_required():
    if current_user.hcp_role == True:
        pass
    else:
        return abort(404)

@health_care_provider.route('/hcp')
def index():
    return render_template('./hcp/index.html')


@health_care_provider.route('/hcpmain',methods=['GET','POST'])
@login_required
def hcpmain():
    hcp_required()
    user=None
    if request.method =='POST':
        fhssid = request.form['fhssid']
        user = Enrollee.query.filter_by(fhss=fhssid).first()
        if user:
            return render_template('./hcp/dashboard.html', user=user)

        else:
            flash('FHSS ID does not exist')
            return redirect(url_for('hcp.hcpmain'))

    return render_template('./hcp/dashboard.html',user=user)

@health_care_provider.route('/eprofile/<int:id>',methods=['GET','POST'])
@login_required
def eprofile(id):
    hcp_required()
    if request.method == 'POST':
        logger(id)
        user = Enrollee.query.filter_by(id=id).first()
        post_cost = request.form['post_cost']
        ailment = request.form['ailment']
        user.post_cost +=int(post_cost)
        user.ailment = ailment
        db.session.flush()
        db.session.commit()
        
        return render_template('/hcp/profile.html', user=user)
    user = Enrollee.query.filter_by(id=id).first()
    return render_template('/hcp/profile.html', user=user)

    


@health_care_provider.route('/eprocess/<int:id>',methods=['GET','POST'])
def eprocess(id):
    hcp_required()
    
    if request.method=='POST':
        sent_otp=request.form['otp']
        check_otp = otp.query.filter_by(id=id).first()
        if check_otp == sent_otp:
            flash('verified please close')
            return redirect(url_for('hcp.eprofile',id=check_otp.user_id  ))

    user = Enrollee.query.filter_by(id=id).first()
    ur_id = shortuuid.ShortUUID().random(length=3)
    sms = client.send_message({
        'from': current_user.hospital_name,
        'to': user.phone,
        'text': 'your opt is '+str(ur_id)

    })
    new_otp = otp(token=ur_id, expire='6000',
                  user_id=user.id)
    flash('One time password has been sent')
    return redirect(url_for('hcp.main'))


@health_care_provider.route('/hcp/logout')
def logout():
	logout_user()
	flash("sign out successful")
	return redirect(url_for('homepage.home'))

Health/recordssystem/hmoss/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for,abort
from werkzeug.security import generate_password_hash, check_password_hash
import random
from models.Hcp import *
from models.enrollee import * 
import shortuuid
import nexmo


hmos = Blueprint('hmos', __name__)
def hmo_required():
    if current_user.hmo_role == False:
        return abort(404)
    else:
        pass

@hmos.route('/hmo')
def homehmo():
    return render_template('./hmo/index.html')


@hmos.route('/hmain')
@login_required
def main():
    hmo_required()
    user = Enrollee.query.order_by(
        Enrollee.date_registerd.desc()).all()
    return render_template('./hmo/dashboard.html',user=user)


@hmos.route('/hprofile/<int:id>')
@login_required
def hprofile(id):
    hmo_required()
    user = Enrollee.query.filter_by(id=id).first()
    return render_template('/hmo/profile.html', user=user)

@hmos.route('/hsignup')

def hsignup():
    
    return render_template('hmo/signup/index.html')

@hmos.route('/view/<int:id>')
@login_required
def view(id):
    hmo_required()
    user = Histories.query.filter_by(Hospital_ID=id).all()
    return render_template('./hmo/view/index.html', user=user)

@hmos.route('/claim')
@login_required
def claim():
    hmo_required()
    new_claim = payments_claims(Hmo_Name=current_user.organ, Hmo_ID=current_user.id,
                                hmo_reg_no=current_user.hmo_reg_no)
    db.session.add(new_claim)
    db.session.commit()
    flash('claim notification has been sent to the FHSS')
    return redirect(url_for('hmos.main'))

@hmos.route('/view_claims')
@login_required
def view_claims():
    hmo_required()
    user = payments_claims.query.filter_by(Hmo_ID=current_user.id).all()
    return render_template('./hmo/view/payments.html', user=user)

    

Health/recordssystem/templates/fhss/hcp/hcp.html
<!doctype html>
<html lang="en">

<head>
	{% include './hmo/links.html' %}

</head>


<body>
	<!-- WRAPPER -->
	<div id="wrapper">
		<!-- NAVBAR -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="brand">
					<a href="#">
						<img style="width:100px; height:50px;" src="{{url_for('static',filename='HCP/assets/img/logo-dark.png')}}" alt="">
					</a>
				</div>
				<div class="container-fluid">
					<div class="navbar-btn">
						<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
					</div>
					
			
			</nav>
		<!-- END NAVBAR -->
		<!-- LEFT SIDEBAR -->
		<div id="sidebar-nav" class="sidebar">
			<div class="sidebar-scroll">
				<nav>
					<ul class="nav">
						<br><br>
						<li><a href="{{url_for('fhss.fmain')}}"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
						<li><a href="{{url_for('fhss.fhenrol')}}"><i class="lnr lnr-linearicons"></i> <span>View all enrollee</span></a></li>
						<li><a href="{{url_for('fhss.fhcp')}}"><i class="lnr lnr-linearicons"></i> <span>View all HCP</span></a></li>
						<li><a href="{{url_for('fhss.fmain')}}"><i class="lnr lnr-linearicons"></i> <span>View all HMO</span></a></li>
				
				
						<li><a href="/logout" class=""><i class="lnr lnr-code"></i> <span>logout</span></a></li>
				
					</ul>
				</nav>
			</div>
		</div>
		
		<!-- END LEFT SIDEBAR -->
		<script>

			/* Trigger flash modal */
			$(document).ready(function () {
				var messages = "{{ get_flashed_messages() }}";

				if (typeof messages != 'undefined' && messages != '[]') {
					$("#myModal").modal();
				};
			});
		</script>
		<!-- MAIN -->

		<div id="wrapper">
			<div id="myModal" class="modal fade" role="dialog">
				<div class="modal-dialog">
		
					<!-- Modal content-->
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							<h4 class="modal-title">FHSS PROMPT</h4>
						</div>
						<div class="modal-body">
							{% with messages = get_flashed_messages() %}
							{% if messages %}
							<ul class=flashes>
								{% for message in messages %}
								<li>{{ message }}</li>
								{% endfor %}
							</ul>
							{% endif %}
							{% endwith %}
							
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</div>
		
				</div>
			</div>
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<div class="container-fluid">
						<h3 class="page-title">Tables</h3>
						<div class="row">
							<div>
								<!-- BASIC TABLE -->
								<div class="panel">
									<div class="panel-heading">
										<h3 class="panel-title">Basic Table</h3>
									</div>
									<div class="panel-body">

										<table  id="myTable" class="table">
							
											<thead>
												<tr>
													<th>HOSPTAL NAME</th>
													<th>Meical Registration Number</th>
													<th>Tax id</th>
													<th>RC Number</th>
													<th>Account Status</th>
													<th>View</th>
												</tr>
											</thead>
											{% for users in hcp %}
												{% if users.hospital_name == None %}
													<i></i>
												{% else %}

											<tbody>
												<tr>
													<td>{{users.hospital_name}}</td>
													<td>{{users.medical_regno}}</td>
													<td>{{users.tax_id}}</td>
													<td>{{users.rc_number}}</td>
														{% if users.block==True %}
															<td style="color:red;">suspended</td>
														{%  else %}
															<td style="color:blue;">Active</td>
														{% endif %}
													<td>
													<div class="text-center"><a href="{{url_for('fhss.hcp_view',id=users.id)}}" class="btn btn-primary">View Profile</a></div>

													</td>

											</tbody>
												{% endif %}
											{% endfor %}
										</table>
										
									</div>
								</div>
							
								<!-- END BASIC TABLE -->
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
	
		<!-- END MAIN -->
		<div class="clearfix"></div>
		<footer>
			<div class="container-fluid">
				<p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
			</div>
		</footer>
	</div>
	<!-- END WRAPPER -->
	<!-- Javascript -->
	<script src="static/HCP/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script src="static/HCP/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
	<script src="static/HCP/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
	<script src="static/HCP/assets/vendor/chartist/js/chartist.min.js"></script>
	<script src="static/HCP/assets/scripts/klorofil-common.js"></script>
	
</body>

</html>

Health/recordssystem/templates/fhss/hcp/profile.html
<!doctype html>
<html lang="en">

<head>
	<title>Profile | Klorofil - Free Bootstrap Dashboard Template</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="{{url_for('static', filename='HCP/assets/vendor/bootstrap/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{url_for('static',filename='HCP/assets/vendor/font-awesome/css/font-awesome.min.css')}}">
	<link rel="stylesheet" href="{{url_for('static',filename='HCP/assets/vendor/linearicons/style.css')}}">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="{{url_for('static',filename='HCP/assets/css/main.css')}}">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">
</head>

<body>

<script>

	/* Trigger flash modal */
		$(document).ready(function () {
			var messages = "{{ get_flashed_messages() }}";

			if (typeof messages != 'undefined' && messages != '[]') {
				$("#myModal").modal();
			};
		});
</script>
	<!-- WRAPPER -->
	<div id="wrapper">
		<div id="myModal" class="modal fade" role="dialog">
			<div class="modal-dialog">
		
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">FHSS PROMPT</h4>
					</div>
					<div class="modal-body">
						{% with messages = get_flashed_messages() %}
						{% if messages %}
						<ul class=flashes>
							{% for message in messages %}
							<li>{{ message }}</li>
							{% endfor %}
						</ul>
						{% endif %}
						{% endwith %}
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
				</div>
		
			</div>
		</div>
		<!-- NAVBAR -->
						<nav class="navbar navbar-default navbar-fixed-top">
							<div class="brand">
								<a href="#">
									<img style="width:100px; height:50px;" src="{{url_for('static',filename='HCP/assets/img/logo-dark.png')}}" alt="">
								</a>
							</div>
							<div class="container-fluid">
								<div class="navbar-btn">
									<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
								</div>
						
						
						</nav>

		<!-- END NAVBAR -->
		<!-- LEFT SIDEBAR -->
<li><a href="{{url_for('fhss.fmain')}}"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
<li><a href="{{url_for('fhss.fhenrol')}}"><i class="lnr lnr-linearicons"></i> <span>View all enrollee</span></a></li>
<li><a href="{{url_for('fhss.fhcp')}}"><i class="lnr lnr-linearicons"></i> <span>View all HCP</span></a></li>
<li><a href="{{url_for('fhss.fmain')}}"><i class="lnr lnr-linearicons"></i> <span>View all HMO</span></a></li>


<li><a href="/logout" class=""><i class="lnr lnr-code"></i> <span>logout</span></a></li>
		<!-- END LEFT SIDEBAR -->
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<div class="panel panel-profile">
						<div class="clearfix">
							<!-- LEFT COLUMN -->
							<div>
								<!-- PROFILE HEADER -->
								<div class="profile-header">
									<div class="overlay"></div>
									<div class="profile-main">
										<h1>{{user.hospital_name}}</h1>
										
										<span class="online-status status-available">Available</span>
									</div>
									<div class="profile-stat">
										<div class="row">
					
											</div>
										</div>
									</div>
								</div>
								<!-- END PROFILE HEADER -->
								<!-- PROFILE DETAIL -->
								<div class="profile-detail">
									<div class="profile-info">
										<h4 class="heading">Basic Info</h4>
										<ul class="list-unstyled list-justify">
											<li>Hospital Name <span>{{user.hospital_name}}</span></li>
											<li>Address <span>{{user.address}}</span></li>
											<li>Medical Registration Number <span>{{user.medical_regno}}</span></li>
											<li>RC Number <span>{{user.rc_number}}</span></li>
											<li>Tax id <span>{{user.tax_id}}</span></li>
											<li>Date Registerd <span>{{user.date_registerd}}</span></li>
											<li>Post Cost <span>{{user.post_cost}}</span></li>
		
										</ul>
									</div>
									<div class="text-center"><a href="{{url_for('fhss.view_history',id=user.id)}}" class="btn btn-primary">View Visited Enrollee</a></div>
								</div>
								<!-- END PROFILE DETAIL -->
							</div>
							<!-- END LEFT COLUMN -->
							<!-- RIGHT COLUMN -->
							
						</div>
					</div>
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
		<!-- END MAIN -->
		<div class="clearfix"></div>
		<footer>
			<div class="container-fluid">
				<p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
			</div>
		</footer>
	</div>
	<!-- END WRAPPER -->
	<!-- Javascript -->
	<script src="{{url_for('static',filename='HCP/assets/vendor/jquery/jquery.min.js')}}"></script>
	<script src="{{url_for('static',filename='HCP/assets/vendor/bootstrap/js/bootstrap.min.js')}}"></script>
	<script src="{{url_for('static',filename='HCP/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
	<script src="{{url_for('static',filename='HCP/assets/scripts/klorofil-common.js')}}}"></script>
</body>

</html>

Health/recordssystem/templates/fhss/hcp/view.html
<!doctype html>
<html lang="en">

<head>
	{% include './hmo/links.html' %}

</head>


<body>
	<!-- WRAPPER -->
	<div id="wrapper">
		<!-- NAVBAR -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="brand">
					<a href="#">
						<img style="width:100px; height:50px;" src="{{url_for('static',filename='HCP/assets/img/logo-dark.png')}}" alt="">
					</a>
				</div>
				<div class="container-fluid">
					<div class="navbar-btn">
						<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
					</div>
					
			
			</nav>
		<!-- END NAVBAR -->
		<!-- LEFT SIDEBAR -->
		<div id="sidebar-nav" class="sidebar">
			<div class="sidebar-scroll">
				<nav>
					<ul class="nav">
						<br><br>
						<li><a href="{{url_for('fhss.fmain')}}"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
						<li><a href="{{url_for('fhss.fhenrol')}}"><i class="lnr lnr-linearicons"></i> <span>View all enrollee</span></a></li>
						<li><a href="{{url_for('fhss.fhcp')}}"><i class="lnr lnr-linearicons"></i> <span>View all HCP</span></a></li>
						<li><a href="{{url_for('fhss.fmain')}}"><i class="lnr lnr-linearicons"></i> <span>View all HMO</span></a></li>
						
						
						<li><a href="/logout" class=""><i class="lnr lnr-code"></i> <span>logout</span></a></li>
				
					</ul>
				</nav>
			</div>
		</div>
		<!-- END LEFT SIDEBAR -->
		<script>

			/* Trigger flash modal */
			$(document).ready(function () {
				var messages = "{{ get_flashed_messages() }}";

				if (typeof messages != 'undefined' && messages != '[]') {
					$("#myModal").modal();
				};
			});
		</script>
		<!-- MAIN -->

		<div id="wrapper">
			<div id="myModal" class="modal fade" role="dialog">
				<div class="modal-dialog">
		
					<!-- Modal content-->
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							<h4 class="modal-title">Modal Header</h4>
						</div>
						<div class="modal-body">
							{% with messages = get_flashed_messages() %}
							{% if messages %}
							<ul class=flashes>
								{% for message in messages %}
								<li>{{ message }}</li>
								{% endfor %}
							</ul>
							{% endif %}
							{% endwith %}
						
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</div>
		
				</div>
			</div>
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					<div class="container-fluid">
						<h3 class="page-title">Tables</h3>
						<div class="row">
							<div>
								<!-- BASIC TABLE -->
								<div class="panel">
									<div class="panel-heading">
										<h3 class="panel-title">Basic Table</h3>
									</div>
									<div class="panel-body">

										<table  id="myTable" class="table">
							
											<thead>
												<tr>
													<th>HOSPTAL NAME</th>
													<th>Enrollee Name</th>
													<th>Enrollee FHSS ID</th>
													<th>Enrollee NIN</th>
													<th>Date / Time of visit</th>
												</tr>
											</thead>
											{% for users in user %}
												

											<tbody>
												<tr>
													<td>{{users.hospital_name}}</td>
													<td>{{users.Hospital_Name}}</td>
													<td>{{users.Patient_name}}</td>
													<td>{{users.Patient_fhss}}</td>
													<td>{{users.Patient_nin}}</td>
													<td>{{users.date_time}}</td>

											</tbody>
											{% endfor %}
										</table>
										
									</div>
								</div>
							
								<!-- END BASIC TABLE -->
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
	
		<!-- END MAIN -->
		<div class="clearfix"></div>
		<footer>
			<div class="container-fluid">
				<p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
			</div>
		</footer>
	</div>
	<!-- END WRAPPER -->
	<!-- Javascript -->
	<script src="{{url_for('static',filename='HCP/assets/vendor/bootstrap/js/bootstrap.min.js')}}"></script>
	<script src="{{url_for('static',filename='HCP/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
	<script src="{{url_for('static',filename='HCP/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js')}}"></script>
	<script src="{{url_for('static',filename='HCP/assets/vendor/chartist/js/chartist.min.js')}}"></script>
	<script src="{{url_for('static',filename='HCP/assets/scripts/klorofil-common.js')}}"></script>
	
</body>

</html>